services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
    working_dir: /home/dynamodblocal
    ports:
      - "8000:8000"
    volumes:
      - ./.dynamodb:/home/dynamodblocal/data
