service: serverless-users-service
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: us-east-1

  logRetentionInDays: 7

  httpApi:
    cors: true

  environment:
    NODE_ENV: ${env:STAGE, 'dev'}
    NODE_OPTIONS: --enable-source-maps
    USERS_TABLE: ${env:USERS_TABLE, 'users-service-db'}
    REGION: ${env:REGION, 'us-east-1'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.usersTableName}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.usersTableName}/index/*

package:
  patterns:
    - "!**/*.test.ts"
    - "!**/*.spec.ts"
    - "!README.md"
    - "!TODO.md"
    - "!DONE.md"

custom:
  dotenv:
    path: .env.${sls:stage}
  usersTableName: users-service-db

# Por ahora lo dejamos vac√≠o: vas a ir agregando handlers poco a poco.
functions:
  createUser:
    handler: src/functions/users/create.handler
    events:
      - httpApi:
          method: POST
          path: /users
  getUserById:
    handler: src/functions/users/get-by-id.handler
    events:
      - httpApi:
          method: GET
          path: /users/{id}
  getUserByEmail:
    handler: src/functions/users/get-by-email.handler
    events:
      - httpApi:
          method: GET
          path: /users/by-email
  listUsers:
    handler: src/functions/users/list.handler
    events:
      - httpApi:
          method: GET
          path: /users
  updateUser:
    handler: src/functions/users/update.handler
    events:
      - httpApi:
          method: PUT
          path: /users/{id}

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

  Outputs:
    UsersTableName:
      Value: ${self:custom.usersTableName}
